export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS'

export const REQUEST_STARTED = 'REQUEST_STARTED';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const SET_VISIBLE_POPUP_NAME = 'SET_VISIBLE_POPUP_NAME';
export const SET_SEARCH_TEXT = 'SET_SEARCH_TEXT';
export const SET_SELECTED_SORT = 'SET_SELECTED_SORT';
export const SET_SELECTED_GENRE = 'SET_SELECTED_GENRE';