export const FETCH_MOVIES_STARTED = 'FETCH_MOVIES_STARTED';
export const FETCH_MOVIES_SUCCESS = 'FETCH_MOVIES_SUCCESS';
export const FETCH_MOVIES_FAILURE = 'FETCH_MOVIES_FAILURE';

export const CREATE_MOVIE_STARTED = 'CREATE_MOVIE_STARTED';
export const CREATE_MOVIE_SUCCESS = 'CREATE_MOVIE_SUCCESS';
export const CREATE_MOVIE_FAILURE = 'CREATE_MOVIE_FAILURE';

export const UPDATE_MOVIE_STARTED = 'UPDATE_MOVIE_STARTED';
export const UPDATE_MOVIE_SUCCESS = 'UPDATE_MOVIE_SUCCESS';
export const UPDATE_MOVIE_FAILURE = 'UPDATE_MOVIE_FAILURE';

export const DELETE_MOVIE_STARTED = 'DELETE_MOVIE_STARTED';
export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';
export const DELETE_MOVIE_FAILURE = 'DELETE_MOVIE_FAILURE';

export const SET_VIEWED_MOVIE = 'SET_VIEWED_MOVIE';
export const SET_VISIBLE_POPUP_NAME = 'SET_VISIBLE_POPUP_NAME';