export const TITLE_PLACEHOLDER = 'Title here'
export const DATE_PLACEHOLDER = 'Select Date'
export const MOVIE_URL_PLACEHOLDER = 'Movie URL here'
export const GENRE_PLACEHOLDER = 'Genre here'
export const OVERVIEW_PLACEHOLDER = 'Overview here'
export const RUNTIME_PLACEHOLDER = 'Runtime here'
export const RESET = 'RESET'